name: builder

on: push

jobs:
  job-14-jre:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (14-jre)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf,linux/s390x \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/master" ]] && echo true || echo false)" \
            -f 14-jre.Dockerfile -t jcxldn/openjdk-alpine:14-jre .
  job-14-jdk-slim:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (14-jdk-slim)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        # linux/s390x throws SIGILL, so has been disabled.
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/master" ]] && echo true || echo false)" \
            -f 14-jdk-slim.Dockerfile -t jcxldn/openjdk-alpine:14-jdk-slim .
  job-14-jdk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (14-jdk)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        # linux/s390x throws SIGILL, so has been disabled.
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/master" ]] && echo true || echo false)" \
            -f 14-jdk.Dockerfile -t jcxldn/openjdk-alpine:14-jdk .
  job-8-jre:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (8-jre)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf,linux/s390x \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/master" ]] && echo true || echo false)" \
            -f 8-jre.Dockerfile -t jcxldn/openjdk-alpine:8-jre .
  job-8-jdk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (8-jdk)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        # linux/s390x throws SIGILL, so has been disabled.
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/master" ]] && echo true || echo false)" \
            -f 8-jdk.Dockerfile -t jcxldn/openjdk-alpine:8-jdk .
