name: builder

on:
  push:
    branches: master

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (14-jre)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf,linux/s390x \
            --output "type=image,push=true" \
            -f 14-jre.Dockerfile -t jcxldn/openjdk-alpine:14-jre .
