name: builder

on: push

jobs:
  job-14-jdk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (14-jdk)
        # linux/386, linux/arm temporarily disabled.
        # linus/ppc64le currently does not work due to an unknown privilege violation. (might be qemu?)
        # linux/s390x throws SIGILL, so has been disabled.
        run: |
          docker buildx build \
            --platform linux/armhf \
            --output "type=image,push=false" \
            -f 14-jdk.Dockerfile -t jcxldn/openjdk-alpine:14-jdk .
 
